### ISSUE TITLE
gzip file in alignments

### ISSUE THREAD

**Issue by amromics** [amromics/amromics#6]
In the alignment folder of collection, alignment file (.fna.aln and .faa.aln) can be gzip'ed to save space. Input files (.fna and .faa) can be constructed from the alignment files, and hence can be removed.
Note @leducquangpm : After this is updated, will make sure amrviz can read gzip alignment files

**Comment by ntanh1999** [comment]
I have already made these changes: gzip the protein and nucleotide alignment files as well as remove input files. I also changed extract_json.py in AMRviz so that it can accept compressed alignment files.

**Comment by amromics** [comment]
that is great. Thanks

**Comment by amromics** [comment]
resolved!
